<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto

namespace GPBMetadata;

class AiService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ò
ai_service.proto
ai_service"/
TeamsRequest
teams (2.ai_service.Team"B
PredictionsResponse+
predictions (2.ai_service.Prediction"$
Team
name (	
points (".

Prediction
team (	

prediction (	2l
PredictionServiceW
GetChampionshipPredictions.ai_service.TeamsRequest.ai_service.PredictionsResponseB7Z)github.com/imediasun/ai_service/generated 	Generatedbproto3'
        , true);

        static::$is_initialized = true;
    }
}

