#!/bin/sh
prepare () {
cd $1
if [ ! -e .env ]; then
   echo "Coping .env.example on .env, because .env absent in laravel dir"
   cp -f .env.example .env;
fi;

#chown www-data -R /var/www/excursions.back
}
cd /var/www/excursions.back
composer install

set -x
prepare "/var/www/excursions.back/"
set +x

cd /var/www/Microservices/sitelogger/laravel
if [ ! -e .env ]; then
   echo "Coping .env.example on .env, because .env absent in laravel dir"
   cp -f .env.example .env;
fi;
composer install

set -x
prepare "/var/www/Microservices/sitelogger/"
set +x

cd /var/www/excursions.back/public/
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
   set -- apache2-foreground "$@"
fi

exec "$@"
